traefik:
  ingressClass:
    enabled: false

  gateway:
    enabled: true

  gatewayClass:
    enabled: true

  api:
    dashboard: true
    insecure: true

  # -- Only dashboard & healthcheck IngressRoute are supported.
  # It's recommended to create workloads CR outside of this Chart.
  # @default -- See _values.yaml_
  ingressRoute:
    dashboard:
      enabled: true
      services:
        - name: api@internal
          kind: TraefikService
      entryPoints: ["web"]

  providers:
    kubernetesCRD:
      enabled: true
      allowCrossNamespace: true

    kubernetesGateway:
      enabled: true

  log:
    format: json # @schema enum:["common", "json", null]; type:[string, null]; default: "common"
    level: "INFO" # @schema enum:[TRACE,DEBUG,INFO,WARN,ERROR,FATAL,PANIC]; default: "INFO"

  accessLog:
    enabled: true
    format: json # @schema enum:["common", "genericCLF", "json", null]; type:[string, null]; default: "common"

  service:
    enabled: true
    spec:
      type: ClusterIP
