traefik:
  ingressClass:
    enabled: false

  gateway:
    enabled: false

  gatewayClass:
    enabled: false

  api:
    dashboard: true
    insecure: true

  ingressRoute:
    dashboard:
      enabled: true
      services:
        - name: api@internal
          kind: TraefikService
      entryPoints: ["web"]

  providers:
    kubernetesCRD:
      enabled: true
      allowCrossNamespace: true

    kubernetesGateway:
      enabled: false

  log:
    format: json # @schema enum:["common", "json", null]; type:[string, null]; default: "common"
    level: "INFO" # @schema enum:[TRACE,DEBUG,INFO,WARN,ERROR,FATAL,PANIC]; default: "INFO"

  accessLog:
    enabled: true
    format: json # @schema enum:["common", "genericCLF", "json", null]; type:[string, null]; default: "common"

  service:
    enabled: true
    spec:
      type: NodePort

  ports:
    web:
      nodePort: 30080
