{{- if .Values.scaling -}}
{{- if eq .Values.scaling.min .Values.scaling.max }}
{{- fail "The scaling min and max field cannot be equal" }}
{{- end }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "web.fullname" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "web.fullname" . }}
  minReplicas: {{ .Values.scaling.min }}
  maxReplicas: {{ .Values.scaling.max }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.scaling.target }}
{{- end }}
