apiVersion: v1
kind: Service
metadata:
  name: {{ include "web.fullname" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    {{- include "web.selectorLabels" . | nindent 4 }}
  type: ClusterIP
