name: deploy
on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
        description: The hash for image tag - the release id
    secrets:
      pat_write_token:
        required: true
        description: Required to commit in external repository

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          path: open-idp-apps
          ref: main
          repository: jasondavindev/open-idp-apps
          token: ${{ secrets.pat_write_token }}

      - name: prepare
        id: prepare
        shell: bash
        env:
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          set -euo pipefail

          APP_NAME="$(echo "${GITHUB_REPOSITORY}" | cut -d / -f 2)"
          OPEN_IDP_DIR="open-idp-apps/apps/${APP_NAME}"

          cp -r .idp/* "${OPEN_IDP_DIR}/"
          cd $OPEN_IDP_DIR

          VALUES_FILE="values.yaml"

          if [[ ! -f "${VALUES_FILE}" ]]; then
              echo "values file not found: ${VALUES_FILE}"
              exit 1
          fi

          if [[ -z "${IMAGE_TAG}" ]]; then
              echo "Invalid image tag"
              exit 1
          fi

          yq -i \
              '.global.image.tag = strenv(IMAGE_TAG)' \
              "${VALUES_FILE}"

          if git diff --quiet -- "${VALUES_FILE}"; then
              echo "values.yaml is up to date ${IMAGE_TAG}"
              exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          MESSAGE="chore(cd): bump ${APP_NAME} image tag to ${IMAGE_TAG} [skip ci]"

          git add "${VALUES_FILE}"
          git commit -m "$MESSAGE"
          echo "$MESSAGE"

          {
            echo "OPEN_IDP_DIR=${OPEN_IDP_DIR}"
          } >>"${GITHUB_ENV}"

      - name: deploy
        shell: bash
        run: |
          set -euo pipefail

          git pull --rebase origin main

          if git push --force origin main; then
            exit 0
          fi

          exit 1
